# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false
  # List of build tags, all linters use it.
  # Default: [].
  build-tags:
    - mytag
  modules-download-mode: readonly
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false
  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
  go: '1.23'
issues:
  exclude-files:
  exclude-dirs:
  exclude-dirs-use-default: false
linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    #    - contextcheck
    - cyclop
    - decorder
    #    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    #    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    #    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    #    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    #    - godot
    #    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    #    - gosec
    - gosimple
    #    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    #    - interfacer
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    #    - misspell
    - musttag
    - nakedret
    #    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    #    - tagalign
    #    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    #    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    #    - asasalint
    #    - asciicheck
    #    - bidichk
    #    - bodyclose
    #    - containedctx
    - contextcheck
    #    - cyclop
    #    - decorder
    - depguard
    #    - dogsled
    #    - dupl
    #    - dupword
    #    - durationcheck
    #    - errcheck
    #    - errchkjson
    #    - errname
    #    - errorlint
    #    - exhaustive
    - exhaustruct
    #    - forbidigo
    #    - forcetypeassert
    #    - funlen
    - gci
    #    - ginkgolinter
    #    - gocheckcompilerdirectives
    - gochecknoglobals
    #    - gochecknoinits
    #    - gocognit
    #    - goconst
    #    - gocritic
    #    - gocyclo
    - godot
    - godox
    #    - gofmt
    #    - gofumpt
    #    - goheader
    #    - goimports
    #    - gomoddirectives
    #    - gomodguard
    #    - goprintffuncname
    - gosec
    #    - gosimple
    - gosmopolitan
    #    - govet
    #    - grouper
    #    - importas
    #    - ineffassign
    #    - interfacebloat
    #    - interfacer
    #    - ireturn
    #    - lll
    #    - loggercheck
    #    - maintidx
    #    - makezero
    #    - mirror
    - misspell
    #    - musttag
    #    - nakedret
    - nestif
    #    - nilerr
    #    - nilnil
    #    - nlreturn
    #    - noctx
    #    - nolintlint
    #    - nonamedreturns
    #    - nosprintfhostport
    #    - paralleltest
    #    - prealloc
    #    - predeclared
    #    - promlinter
    #    - reassign
    #    - revive
    #    - rowserrcheck
    #    - sqlclosecheck
    #    - staticcheck
    #    - stylecheck
    - tagalign
    - tagliatelle
    #    - tenv
    #    - testableexamples
    #    - testpackage
    #    - thelper
    #    - tparallel
    #    - typecheck
    #    - unconvert
    #    - unparam
    #    - unused
    #    - usestdlibvars
    - varnamelen
  #    - wastedassign
  #    - whitespace
  #    - wrapcheck
  #    - wsl
  #    - zerologlint
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true
